/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kierjohn.testgui;

import java.awt.*;
import java.io.IOException;
import java.text.ParseException;
import javax.swing.*;

/**
 *
 * @author LENOVO
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        askModePanel = new javax.swing.JPanel();
        gotoQuizCreation = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        gotoQuizGame = new javax.swing.JButton();
        quizSetupPanel = new javax.swing.JPanel();
        quizSetupPanelArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        qDiffInput = new javax.swing.JComboBox<>();
        qCatInput = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        qAmountInput = new javax.swing.JSpinner();
        playGameBtn = new javax.swing.JButton();
        gotoMain3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        qTypeInput = new javax.swing.JComboBox<>();
        notificationLabel = new javax.swing.JLabel();
        quizFinishedPanel = new javax.swing.JPanel();
        questionLabel1 = new javax.swing.JLabel();
        resultScoreCountLabel = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        resultCorrectAnswersLabel = new javax.swing.JLabel();
        playGameBtn1 = new javax.swing.JButton();
        gotoMain = new javax.swing.JButton();
        invalidDataPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        backToSetupBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        quizCreationPanel = new javax.swing.JPanel();
        addQuestionForm = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionFormContainerPanel = new javax.swing.JPanel();
        gotoMain2 = new javax.swing.JButton();
        addQuestionForm1 = new javax.swing.JButton();
        addQuestionForm2 = new javax.swing.JButton();
        quizCreateQuestionCount = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        quizMainPanel = new javax.swing.JPanel();
        gameInfoPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        difficultyLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        questionCounterLabel = new javax.swing.JLabel();
        gotoMain4 = new javax.swing.JButton();
        quizBottomLabel = new javax.swing.JPanel();
        questionPanel = new com.kierjohn.testgui.QuestionPanel();
        confirmPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        gotoMainConfirmNoBtn = new javax.swing.JButton();
        gotoMainConfirmYesBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("mainFrame"); // NOI18N
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setPreferredSize(new java.awt.Dimension(976, 763));
        mainPanel.setLayout(new java.awt.CardLayout());

        askModePanel.setBackground(new java.awt.Color(51, 51, 51));
        askModePanel.setPreferredSize(new java.awt.Dimension(960, 540));

        gotoQuizCreation.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        gotoQuizCreation.setText("Create Custom Quiz");
        gotoQuizCreation.setDefaultCapable(false);
        gotoQuizCreation.setFocusPainted(false);
        gotoQuizCreation.setName("playQuizBtn"); // NOI18N
        gotoQuizCreation.setPreferredSize(new java.awt.Dimension(128, 32));
        gotoQuizCreation.setRequestFocusEnabled(false);
        gotoQuizCreation.setRolloverEnabled(false);
        gotoQuizCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoQuizCreationActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("JetBrains Mono", 1, 32)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(250, 242, 249));
        jLabel9.setText("WELCOME WONDERHOY!!!");

        gotoQuizGame.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        gotoQuizGame.setText("Go to Quiz Game");
        gotoQuizGame.setDefaultCapable(false);
        gotoQuizGame.setName("playQuizBtn"); // NOI18N
        gotoQuizGame.setPreferredSize(new java.awt.Dimension(128, 32));
        gotoQuizGame.setRequestFocusEnabled(false);
        gotoQuizGame.setRolloverEnabled(false);
        gotoQuizGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoQuizGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout askModePanelLayout = new javax.swing.GroupLayout(askModePanel);
        askModePanel.setLayout(askModePanelLayout);
        askModePanelLayout.setHorizontalGroup(
            askModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, askModePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(askModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, askModePanelLayout.createSequentialGroup()
                        .addComponent(gotoQuizGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(gotoQuizCreation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, askModePanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(44, 44, 44)))
                .addGap(247, 247, 247))
        );
        askModePanelLayout.setVerticalGroup(
            askModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(askModePanelLayout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel9)
                .addGap(58, 58, 58)
                .addGroup(askModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gotoQuizCreation, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gotoQuizGame, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(askModePanel, "askModeCard");

        quizSetupPanel.setBackground(new java.awt.Color(51, 51, 51));
        quizSetupPanel.setOpaque(false);
        quizSetupPanel.setPreferredSize(new java.awt.Dimension(960, 540));

        quizSetupPanelArea.setBackground(new java.awt.Color(51, 51, 51));
        quizSetupPanelArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 0, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 242, 249));
        jLabel1.setText("Number of Questions");

        qDiffInput.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        qDiffInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Hard" }));
        qDiffInput.setToolTipText("");
        qDiffInput.setName("qDiff"); // NOI18N
        qDiffInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qDiffInputActionPerformed(evt);
            }
        });

        qCatInput.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        qCatInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General Knowledge", "Entertainment: Books", "Entertainment: Film", "Entertainment: Music", "Entertainment: Musicals & Theatres", "Entertainment: Television", "Entertainment: Video Games", "Entertainment: Board Games", "Science & Nature", "Science: Computers", "Science: Mathematics", "Mythology", "Sports", "Geography", "History", "Politics", "Art", "Celebrities", "Animals", "Vehicles", "Entertainment: Comics", "Science: Gadgets", "Entertainment: Japanese Anime & Manga", "Entertainment: Cartoon & Animations" }));
        qCatInput.setToolTipText("Choose from a wide range of topics.");
        qCatInput.setName("qCat"); // NOI18N

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(250, 242, 249));
        jLabel5.setText("Difficulty");

        jLabel6.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(250, 242, 249));
        jLabel6.setText("Category");

        qAmountInput.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        qAmountInput.setModel(new javax.swing.SpinnerNumberModel(10, 1, 50, 1));
        qAmountInput.setToolTipText("");
        qAmountInput.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        qAmountInput.setName("qAmount"); // NOI18N
        qAmountInput.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                qAmountInputMouseWheelMoved(evt);
            }
        });

        playGameBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        playGameBtn.setText("Play Game");
        playGameBtn.setDefaultCapable(false);
        playGameBtn.setFocusPainted(false);
        playGameBtn.setName("playQuizBtn"); // NOI18N
        playGameBtn.setPreferredSize(new java.awt.Dimension(128, 32));
        playGameBtn.setRequestFocusEnabled(false);
        playGameBtn.setVerifyInputWhenFocusTarget(false);
        playGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playGameBtnActionPerformed(evt);
            }
        });

        gotoMain3.setBackground(new java.awt.Color(100, 100, 100));
        gotoMain3.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        gotoMain3.setForeground(new java.awt.Color(255, 255, 255));
        gotoMain3.setText("Back to Menu");
        gotoMain3.setBorder(null);
        gotoMain3.setName("playQuizBtn"); // NOI18N
        gotoMain3.setPreferredSize(new java.awt.Dimension(128, 32));
        gotoMain3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoMain3ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("JetBrains Mono", 1, 32)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(250, 242, 249));
        jLabel13.setText("Quiz Setup");

        jLabel16.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(250, 242, 249));
        jLabel16.setText("Question Type");

        qTypeInput.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        qTypeInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Multiple Choice", "Identification", "True or False" }));
        qTypeInput.setToolTipText("");
        qTypeInput.setName("qDiff"); // NOI18N
        qTypeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qTypeInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout quizSetupPanelAreaLayout = new javax.swing.GroupLayout(quizSetupPanelArea);
        quizSetupPanelArea.setLayout(quizSetupPanelAreaLayout);
        quizSetupPanelAreaLayout.setHorizontalGroup(
            quizSetupPanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizSetupPanelAreaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(gotoMain3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quizSetupPanelAreaLayout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(quizSetupPanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quizSetupPanelAreaLayout.createSequentialGroup()
                        .addComponent(playGameBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quizSetupPanelAreaLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(37, 37, 37)
                        .addComponent(qTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
            .addGroup(quizSetupPanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(quizSetupPanelAreaLayout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addGroup(quizSetupPanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quizSetupPanelAreaLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18))
                        .addGroup(quizSetupPanelAreaLayout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addGroup(quizSetupPanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(37, 37, 37)))
                    .addGroup(quizSetupPanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(qCatInput, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qDiffInput, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qAmountInput, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(96, Short.MAX_VALUE)))
            .addGroup(quizSetupPanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quizSetupPanelAreaLayout.createSequentialGroup()
                    .addContainerGap(241, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(236, 236, 236)))
        );
        quizSetupPanelAreaLayout.setVerticalGroup(
            quizSetupPanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizSetupPanelAreaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(gotoMain3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(quizSetupPanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(30, 30, 30)
                .addComponent(playGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(quizSetupPanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(quizSetupPanelAreaLayout.createSequentialGroup()
                    .addGap(88, 88, 88)
                    .addGroup(quizSetupPanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(qAmountInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGap(18, 18, 18)
                    .addGroup(quizSetupPanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(qDiffInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGap(18, 18, 18)
                    .addGroup(quizSetupPanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(qCatInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addContainerGap(165, Short.MAX_VALUE)))
            .addGroup(quizSetupPanelAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(quizSetupPanelAreaLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel13)
                    .addContainerGap(298, Short.MAX_VALUE)))
        );

        notificationLabel.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        notificationLabel.setForeground(new java.awt.Color(250, 242, 249));

        javax.swing.GroupLayout quizSetupPanelLayout = new javax.swing.GroupLayout(quizSetupPanel);
        quizSetupPanel.setLayout(quizSetupPanelLayout);
        quizSetupPanelLayout.setHorizontalGroup(
            quizSetupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizSetupPanelLayout.createSequentialGroup()
                .addGroup(quizSetupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quizSetupPanelLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(notificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizSetupPanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(quizSetupPanelArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        quizSetupPanelLayout.setVerticalGroup(
            quizSetupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizSetupPanelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(quizSetupPanelArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(quizSetupPanel, "quizSetupCard");

        quizFinishedPanel.setBackground(new java.awt.Color(51, 51, 51));

        questionLabel1.setFont(new java.awt.Font("Atkinson Hyperlegible", 1, 50)); // NOI18N
        questionLabel1.setForeground(new java.awt.Color(240, 240, 240));
        questionLabel1.setText("Results:");

        resultScoreCountLabel.setBackground(new java.awt.Color(0, 51, 51));
        resultScoreCountLabel.setFont(new java.awt.Font("Atkinson Hyperlegible", 1, 24)); // NOI18N
        resultScoreCountLabel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel111.setBackground(new java.awt.Color(0, 51, 51));
        jLabel111.setFont(new java.awt.Font("Atkinson Hyperlegible", 1, 24)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(255, 255, 255));
        jLabel111.setText("Total Score:");

        jLabel112.setBackground(new java.awt.Color(0, 51, 51));
        jLabel112.setFont(new java.awt.Font("Atkinson Hyperlegible", 1, 24)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(255, 255, 255));
        jLabel112.setText("Correct Answers:");

        resultCorrectAnswersLabel.setBackground(new java.awt.Color(0, 51, 51));
        resultCorrectAnswersLabel.setFont(new java.awt.Font("Atkinson Hyperlegible", 1, 24)); // NOI18N
        resultCorrectAnswersLabel.setForeground(new java.awt.Color(255, 255, 255));

        playGameBtn1.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        playGameBtn1.setText("New Game");
        playGameBtn1.setName("playQuizBtn"); // NOI18N
        playGameBtn1.setPreferredSize(new java.awt.Dimension(128, 32));
        playGameBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playGameBtn1ActionPerformed(evt);
            }
        });

        gotoMain.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        gotoMain.setText("Main Menu");
        gotoMain.setName("playQuizBtn"); // NOI18N
        gotoMain.setPreferredSize(new java.awt.Dimension(128, 32));
        gotoMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout quizFinishedPanelLayout = new javax.swing.GroupLayout(quizFinishedPanel);
        quizFinishedPanel.setLayout(quizFinishedPanelLayout);
        quizFinishedPanelLayout.setHorizontalGroup(
            quizFinishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizFinishedPanelLayout.createSequentialGroup()
                .addGroup(quizFinishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quizFinishedPanelLayout.createSequentialGroup()
                        .addGroup(quizFinishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quizFinishedPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel112)
                                .addGap(18, 18, 18))
                            .addGroup(quizFinishedPanelLayout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addComponent(jLabel111)
                                .addGap(28, 28, 28)))
                        .addGroup(quizFinishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultCorrectAnswersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultScoreCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(quizFinishedPanelLayout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(questionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizFinishedPanelLayout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(gotoMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(playGameBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(350, Short.MAX_VALUE))
        );
        quizFinishedPanelLayout.setVerticalGroup(
            quizFinishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizFinishedPanelLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(questionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(quizFinishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultCorrectAnswersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel112, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(46, 46, 46)
                .addGroup(quizFinishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel111)
                    .addComponent(resultScoreCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(quizFinishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gotoMain, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playGameBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(294, Short.MAX_VALUE))
        );

        mainPanel.add(quizFinishedPanel, "quizFinishedCard");

        invalidDataPanel.setBackground(new java.awt.Color(51, 51, 51));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        backToSetupBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        backToSetupBtn.setText("Back to Setup");
        backToSetupBtn.setName("playQuizBtn"); // NOI18N
        backToSetupBtn.setPreferredSize(new java.awt.Dimension(128, 32));
        backToSetupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToSetupBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("JetBrains Mono", 1, 32)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(250, 242, 249));
        jLabel8.setText("The data you entered is invalid.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(backToSetupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel8)
                .addGap(69, 69, 69)
                .addComponent(backToSetupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout invalidDataPanelLayout = new javax.swing.GroupLayout(invalidDataPanel);
        invalidDataPanel.setLayout(invalidDataPanelLayout);
        invalidDataPanelLayout.setHorizontalGroup(
            invalidDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invalidDataPanelLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        invalidDataPanelLayout.setVerticalGroup(
            invalidDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invalidDataPanelLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(invalidDataPanel, "invalidDataCard");

        quizCreationPanel.setBackground(new java.awt.Color(51, 51, 51));
        quizCreationPanel.setPreferredSize(new java.awt.Dimension(960, 540));

        addQuestionForm.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        addQuestionForm.setText("Save Quiz");
        addQuestionForm.setName("playQuizBtn"); // NOI18N
        addQuestionForm.setPreferredSize(new java.awt.Dimension(128, 32));

        jLabel10.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(250, 242, 249));
        jLabel10.setText("Question Count:");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        questionFormContainerPanel.setBackground(new java.awt.Color(51, 51, 51));
        questionFormContainerPanel.setLayout(new java.awt.GridLayout(0, 1, 5, 0));
        jScrollPane1.setViewportView(questionFormContainerPanel);

        gotoMain2.setBackground(new java.awt.Color(100, 100, 100));
        gotoMain2.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        gotoMain2.setForeground(new java.awt.Color(255, 255, 255));
        gotoMain2.setText("Back to Menu");
        gotoMain2.setBorder(null);
        gotoMain2.setName("playQuizBtn"); // NOI18N
        gotoMain2.setPreferredSize(new java.awt.Dimension(128, 32));
        gotoMain2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoMain2ActionPerformed(evt);
            }
        });

        addQuestionForm1.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        addQuestionForm1.setText("Add Question");
        addQuestionForm1.setName("playQuizBtn"); // NOI18N
        addQuestionForm1.setPreferredSize(new java.awt.Dimension(128, 32));
        addQuestionForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuestionForm1ActionPerformed(evt);
            }
        });

        addQuestionForm2.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        addQuestionForm2.setText("Clear Form");
        addQuestionForm2.setName("playQuizBtn"); // NOI18N
        addQuestionForm2.setPreferredSize(new java.awt.Dimension(128, 32));
        addQuestionForm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuestionForm2ActionPerformed(evt);
            }
        });

        quizCreateQuestionCount.setFont(new java.awt.Font("JetBrains Mono", 1, 32)); // NOI18N
        quizCreateQuestionCount.setForeground(new java.awt.Color(250, 242, 249));
        quizCreateQuestionCount.setText("0");

        jLabel14.setFont(new java.awt.Font("JetBrains Mono", 1, 32)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(250, 242, 249));
        jLabel14.setText("Quiz Creation");

        javax.swing.GroupLayout quizCreationPanelLayout = new javax.swing.GroupLayout(quizCreationPanel);
        quizCreationPanel.setLayout(quizCreationPanelLayout);
        quizCreationPanelLayout.setHorizontalGroup(
            quizCreationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quizCreationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(quizCreationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quizCreationPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(quizCreationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addQuestionForm, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addQuestionForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addQuestionForm2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(quizCreateQuestionCount)))
                    .addGroup(quizCreationPanelLayout.createSequentialGroup()
                        .addComponent(gotoMain2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel14)))
                .addGap(74, 74, 74))
        );
        quizCreationPanelLayout.setVerticalGroup(
            quizCreationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizCreationPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(quizCreationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gotoMain2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGroup(quizCreationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quizCreationPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(addQuestionForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(addQuestionForm2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addQuestionForm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quizCreateQuestionCount)
                        .addContainerGap())
                    .addGroup(quizCreationPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))))
        );

        mainPanel.add(quizCreationPanel, "quizCreationCard");

        gameInfoPanel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Atkinson Hyperlegible", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Score");

        scoreLabel.setFont(new java.awt.Font("Atkinson Hyperlegible", 1, 32)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(255, 255, 255));
        scoreLabel.setText("0");

        jLabel7.setBackground(new java.awt.Color(0, 51, 51));
        jLabel7.setFont(new java.awt.Font("Atkinson Hyperlegible", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Questions");

        categoryLabel.setBackground(new java.awt.Color(0, 51, 51));
        categoryLabel.setFont(new java.awt.Font("Atkinson Hyperlegible", 1, 16)); // NOI18N
        categoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        categoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        difficultyLabel.setBackground(new java.awt.Color(0, 51, 51));
        difficultyLabel.setFont(new java.awt.Font("Atkinson Hyperlegible", 1, 16)); // NOI18N
        difficultyLabel.setForeground(new java.awt.Color(255, 255, 255));
        difficultyLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel11.setFont(new java.awt.Font("Atkinson Hyperlegible", 1, 32)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("00:00");

        jLabel12.setBackground(new java.awt.Color(0, 51, 51));
        jLabel12.setFont(new java.awt.Font("Atkinson Hyperlegible", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Timer");

        questionCounterLabel.setFont(new java.awt.Font("Atkinson Hyperlegible", 1, 32)); // NOI18N
        questionCounterLabel.setForeground(new java.awt.Color(255, 255, 255));

        gotoMain4.setBackground(new java.awt.Color(100, 100, 100));
        gotoMain4.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        gotoMain4.setForeground(new java.awt.Color(255, 255, 255));
        gotoMain4.setText("Back to Menu");
        gotoMain4.setBorder(null);
        gotoMain4.setName("playQuizBtn"); // NOI18N
        gotoMain4.setPreferredSize(new java.awt.Dimension(128, 32));
        gotoMain4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoMain4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gameInfoPanelLayout = new javax.swing.GroupLayout(gameInfoPanel);
        gameInfoPanel.setLayout(gameInfoPanelLayout);
        gameInfoPanelLayout.setHorizontalGroup(
            gameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameInfoPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(gotoMain4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(gameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameInfoPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(gameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(categoryLabel)
                            .addComponent(difficultyLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 399, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(gameInfoPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(questionCounterLabel)))
                .addGap(34, 34, 34)
                .addGroup(gameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scoreLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41)
                .addGroup(gameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(34, 34, 34))
        );
        gameInfoPanelLayout.setVerticalGroup(
            gameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameInfoPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(gameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, gameInfoPanelLayout.createSequentialGroup()
                            .addGroup(gameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(gameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(scoreLabel)
                                .addComponent(questionCounterLabel)))
                        .addGroup(gameInfoPanelLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel11)))
                    .addComponent(gotoMain4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gameInfoPanelLayout.createSequentialGroup()
                        .addComponent(categoryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(difficultyLabel)))
                .addGap(11, 11, 11))
        );

        quizBottomLabel.setBackground(new java.awt.Color(51, 51, 51));
        quizBottomLabel.setPreferredSize(new java.awt.Dimension(976, 667));
        quizBottomLabel.setLayout(new java.awt.CardLayout());
        quizBottomLabel.add(questionPanel, "quizItem");

        confirmPanel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel15.setBackground(new java.awt.Color(0, 51, 51));
        jLabel15.setFont(new java.awt.Font("Atkinson Hyperlegible", 1, 32)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Are you sure you want to quit?");

        gotoMainConfirmNoBtn.setBackground(new java.awt.Color(100, 100, 100));
        gotoMainConfirmNoBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        gotoMainConfirmNoBtn.setForeground(new java.awt.Color(255, 255, 255));
        gotoMainConfirmNoBtn.setText("No");
        gotoMainConfirmNoBtn.setBorder(null);
        gotoMainConfirmNoBtn.setName("playQuizBtn"); // NOI18N
        gotoMainConfirmNoBtn.setPreferredSize(new java.awt.Dimension(128, 32));
        gotoMainConfirmNoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoMainConfirmNoBtnActionPerformed(evt);
            }
        });

        gotoMainConfirmYesBtn.setBackground(new java.awt.Color(100, 100, 100));
        gotoMainConfirmYesBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        gotoMainConfirmYesBtn.setForeground(new java.awt.Color(255, 255, 255));
        gotoMainConfirmYesBtn.setText("Yes");
        gotoMainConfirmYesBtn.setBorder(null);
        gotoMainConfirmYesBtn.setName("playQuizBtn"); // NOI18N
        gotoMainConfirmYesBtn.setPreferredSize(new java.awt.Dimension(128, 32));
        gotoMainConfirmYesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoMainConfirmYesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout confirmPanelLayout = new javax.swing.GroupLayout(confirmPanel);
        confirmPanel.setLayout(confirmPanelLayout);
        confirmPanelLayout.setHorizontalGroup(
            confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmPanelLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(confirmPanelLayout.createSequentialGroup()
                        .addComponent(gotoMainConfirmYesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gotoMainConfirmNoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        confirmPanelLayout.setVerticalGroup(
            confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(95, 95, 95)
                .addGroup(confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gotoMainConfirmNoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gotoMainConfirmYesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(328, 328, 328))
        );

        quizBottomLabel.add(confirmPanel, "confirmQuit");

        javax.swing.GroupLayout quizMainPanelLayout = new javax.swing.GroupLayout(quizMainPanel);
        quizMainPanel.setLayout(quizMainPanelLayout);
        quizMainPanelLayout.setHorizontalGroup(
            quizMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(quizMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(quizBottomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        quizMainPanelLayout.setVerticalGroup(
            quizMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizMainPanelLayout.createSequentialGroup()
                .addComponent(gameInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 662, Short.MAX_VALUE))
            .addGroup(quizMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quizMainPanelLayout.createSequentialGroup()
                    .addGap(0, 96, Short.MAX_VALUE)
                    .addComponent(quizBottomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        mainPanel.add(quizMainPanel, "quizMainCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        questionPanel.addActionListenerToButtons(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateQuizGameInfo();
            }
        });

        questionPanel.addQPanelButtonActionPerformed();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qDiffInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qDiffInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qDiffInputActionPerformed

    private void playGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playGameBtnActionPerformed
        displayCard(quizBottomLabel, "quizItem");
        String qTypeInputStr = ((String) qTypeInput.getSelectedItem()).toLowerCase();
        String qType;
        switch (qTypeInputStr) {
            case "multiple choice" -> qType = "multiple";
            case "true or false" -> qType = "boolean";
            default -> qType = qTypeInputStr;
        }
        notificationLabel.setText("");
        try {
            qAmountInput.commitEdit();
            APIHandler apiHandler = new APIHandler();
            while (true) {
                try {
                    correctAnswerCount = 0;
                    String category = (String) qCatInput.getSelectedItem();
                    String difficulty = (String) qDiffInput.getSelectedItem();
                    currentQuiz = new Quiz(category);
                    apiHandler.callAPI(
                            (Integer) qAmountInput.getValue(),
                            qCatInput.getSelectedIndex() + 9,
                            difficulty.toLowerCase(),
                            qType
                    );
                    categoryLabel.setText(category);
                    difficultyLabel.setText(difficulty);
                    apiHandler.setAPIResultsToQuiz(currentQuiz);
                    questionCounterLabel.setText("1/" + currentQuiz.getQCount());
                    questionPanel.setCurrentQuestion(currentQuiz.getQuestionAtIndex(currentQuestionIndex = 0));
                    questionPanel.displayQuestion();
                    displayCard(mainPanel, "quizMainCard");
                    break;
                } catch (IOException e) {
                    System.out.println(e.getMessage() + "\nRe-initializing game...\n");
                } catch (APIHandler.MaxAPICallAttemptException e) {
                    System.out.println(e.toString());
                    notificationLabel.setText("Something went wrong. Please try again later.");
                    break;
                }
            }
        } catch (ParseException e) {
            System.out.println("Invalid question amount input.");
            displayCard(mainPanel, "invalidDataCard");
        }
    }//GEN-LAST:event_playGameBtnActionPerformed

    protected void updateQuizGameInfo() {
        if (questionPanel.choiceIsCorrect()) {
            System.out.println("Correct.");
            currentQuizScore += 10;
            correctAnswerCount++;
            scoreLabel.setText(currentQuizScore + "");
        } else {
            System.out.println("Incorrect. The answer is " + currentQuiz.getQuestionAtIndex(currentQuestionIndex).getAnswer() + ".");
        }
        if (currentQuestionIndex == currentQuiz.getQCount() - 1) {
            System.out.println("Current quiz is finished.");
            displayCard(mainPanel, "quizFinishedCard");
            resultCorrectAnswersLabel.setText(correctAnswerCount + "");
            resultScoreCountLabel.setText(scoreLabel.getText());
        } else {
            currentQuestionIndex++;
            questionCounterLabel.setText(currentQuestionIndex + 1 + "/" + currentQuiz.getQCount());
            questionPanel.setCurrentQuestion(currentQuiz.getQuestionAtIndex(currentQuestionIndex));
            questionPanel.displayQuestion();
        }
    }

    private void qAmountInputMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_qAmountInputMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_qAmountInputMouseWheelMoved

    private void playGameBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playGameBtn1ActionPerformed
        displayCard(mainPanel, "quizSetupCard");
    }//GEN-LAST:event_playGameBtn1ActionPerformed

    private void backToSetupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToSetupBtnActionPerformed
        displayCard(mainPanel, "quizSetupCard");
    }//GEN-LAST:event_backToSetupBtnActionPerformed

    private void gotoQuizCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoQuizCreationActionPerformed
        displayCard(mainPanel, "quizCreationCard");
    }//GEN-LAST:event_gotoQuizCreationActionPerformed

    private void gotoQuizGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoQuizGameActionPerformed
        displayCard(mainPanel, "quizSetupCard");
    }//GEN-LAST:event_gotoQuizGameActionPerformed

    private void gotoMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoMainActionPerformed
        displayCard(mainPanel, "askModeCard");
    }//GEN-LAST:event_gotoMainActionPerformed

    private void gotoMain2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoMain2ActionPerformed
        displayCard(mainPanel, "askModeCard");
    }//GEN-LAST:event_gotoMain2ActionPerformed

    private void addQuestionForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuestionForm1ActionPerformed
        questionFormContainerPanel.add(new QuizQuestionForm());
        questionFormContainerPanel.revalidate();
        questionFormContainerPanel.repaint();
        quizCreateQuestionCount.setText(questionFormContainerPanel.getComponentCount() + "");
    }//GEN-LAST:event_addQuestionForm1ActionPerformed

    private void addQuestionForm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuestionForm2ActionPerformed
        questionFormContainerPanel.removeAll();
        questionFormContainerPanel.revalidate();
        questionFormContainerPanel.repaint();
        quizCreateQuestionCount.setText("0");
    }//GEN-LAST:event_addQuestionForm2ActionPerformed

    private void gotoMain3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoMain3ActionPerformed
        displayCard(mainPanel, "askModeCard");
    }//GEN-LAST:event_gotoMain3ActionPerformed

    private void gotoMain4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoMain4ActionPerformed
        displayCard(quizBottomLabel, "confirmQuit");
    }//GEN-LAST:event_gotoMain4ActionPerformed

    private void gotoMainConfirmNoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoMainConfirmNoBtnActionPerformed
        displayCard(quizBottomLabel, "play");
    }//GEN-LAST:event_gotoMainConfirmNoBtnActionPerformed

    private void gotoMainConfirmYesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoMainConfirmYesBtnActionPerformed
        displayCard(quizBottomLabel, "play");
        displayCard(mainPanel, "askModeCard");
    }//GEN-LAST:event_gotoMainConfirmYesBtnActionPerformed

    private void qTypeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qTypeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qTypeInputActionPerformed

    private void displayCard(JComponent container, String cardName) {
        CardLayout card = (CardLayout) container.getLayout();
        card.show(container, cardName);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame frame = new MainFrame();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addQuestionForm;
    private javax.swing.JButton addQuestionForm1;
    private javax.swing.JButton addQuestionForm2;
    private javax.swing.JPanel askModePanel;
    private javax.swing.JButton backToSetupBtn;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JPanel confirmPanel;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JPanel gameInfoPanel;
    private javax.swing.JButton gotoMain;
    private javax.swing.JButton gotoMain2;
    private javax.swing.JButton gotoMain3;
    private javax.swing.JButton gotoMain4;
    private javax.swing.JButton gotoMainConfirmNoBtn;
    private javax.swing.JButton gotoMainConfirmYesBtn;
    private javax.swing.JButton gotoQuizCreation;
    private javax.swing.JButton gotoQuizGame;
    private javax.swing.JPanel invalidDataPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel notificationLabel;
    private javax.swing.JButton playGameBtn;
    private javax.swing.JButton playGameBtn1;
    private javax.swing.JSpinner qAmountInput;
    private javax.swing.JComboBox<String> qCatInput;
    private javax.swing.JComboBox<String> qDiffInput;
    private javax.swing.JComboBox<String> qTypeInput;
    protected javax.swing.JLabel questionCounterLabel;
    private javax.swing.JPanel questionFormContainerPanel;
    private javax.swing.JLabel questionLabel1;
    private com.kierjohn.testgui.QuestionPanel questionPanel;
    private javax.swing.JPanel quizBottomLabel;
    private javax.swing.JLabel quizCreateQuestionCount;
    private javax.swing.JPanel quizCreationPanel;
    private javax.swing.JPanel quizFinishedPanel;
    private javax.swing.JPanel quizMainPanel;
    private javax.swing.JPanel quizSetupPanel;
    private javax.swing.JPanel quizSetupPanelArea;
    private javax.swing.JLabel resultCorrectAnswersLabel;
    private javax.swing.JLabel resultScoreCountLabel;
    protected javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables

    // custom code variables    
    private Quiz currentQuiz;
    private int currentQuestionIndex;
    private int currentQuizScore;
    private int correctAnswerCount;

}
