/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.kierjohn.testgui;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.Random;
import javax.swing.JButton;

/**
 *
 * @author LENOVO
 */
public class QuestionPanel extends javax.swing.JPanel {

    Question currentQuestion;
    String currentChoice;

    /**
     * Creates new form QuestionPanel
     */
    public QuestionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        questionLabel = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        multipleChoicePanel = new javax.swing.JPanel();
        choiceBtn1 = new javax.swing.JButton();
        choiceBtn2 = new javax.swing.JButton();
        choiceBtn3 = new javax.swing.JButton();
        choiceBtn4 = new javax.swing.JButton();
        identificationPanel = new javax.swing.JPanel();
        identificationInputTxtFld = new javax.swing.JTextField();
        identificationSubmitBtn = new javax.swing.JButton();
        trueOrFalsePanel = new javax.swing.JPanel();
        trueBtn = new javax.swing.JButton();
        falseBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(976, 667));

        questionLabel.setBackground(new java.awt.Color(51, 51, 51));
        questionLabel.setFont(new java.awt.Font("JetBrains Mono", 1, 25)); // NOI18N
        questionLabel.setForeground(new java.awt.Color(255, 255, 255));
        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionLabel.setFocusable(false);
        questionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        inputPanel.setBackground(new java.awt.Color(51, 51, 51));
        inputPanel.setForeground(new java.awt.Color(255, 255, 255));
        inputPanel.setLayout(new java.awt.CardLayout());

        multipleChoicePanel.setBackground(new java.awt.Color(51, 51, 51));
        multipleChoicePanel.setForeground(new java.awt.Color(255, 255, 255));
        multipleChoicePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        multipleChoicePanel.setPreferredSize(new java.awt.Dimension(964, 300));
        multipleChoicePanel.setLayout(new java.awt.GridLayout(2, 2));

        choiceBtn1.setBackground(new java.awt.Color(204, 255, 204));
        choiceBtn1.setFont(new java.awt.Font("JetBrains Mono", 1, 25)); // NOI18N
        choiceBtn1.setForeground(new java.awt.Color(0, 102, 204));
        choiceBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        choiceBtn1.setPreferredSize(new java.awt.Dimension(200, 125));
        multipleChoicePanel.add(choiceBtn1);

        choiceBtn2.setBackground(new java.awt.Color(204, 255, 204));
        choiceBtn2.setFont(new java.awt.Font("JetBrains Mono", 1, 25)); // NOI18N
        choiceBtn2.setForeground(new java.awt.Color(0, 102, 204));
        choiceBtn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        choiceBtn2.setPreferredSize(new java.awt.Dimension(200, 125));
        multipleChoicePanel.add(choiceBtn2);

        choiceBtn3.setBackground(new java.awt.Color(204, 255, 204));
        choiceBtn3.setFont(new java.awt.Font("JetBrains Mono", 1, 25)); // NOI18N
        choiceBtn3.setForeground(new java.awt.Color(0, 102, 204));
        choiceBtn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        choiceBtn3.setPreferredSize(new java.awt.Dimension(200, 125));
        multipleChoicePanel.add(choiceBtn3);

        choiceBtn4.setBackground(new java.awt.Color(204, 255, 204));
        choiceBtn4.setFont(new java.awt.Font("JetBrains Mono", 1, 25)); // NOI18N
        choiceBtn4.setForeground(new java.awt.Color(0, 102, 204));
        choiceBtn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        choiceBtn4.setPreferredSize(new java.awt.Dimension(200, 125));
        multipleChoicePanel.add(choiceBtn4);

        choiceBtns = new JButton[] {choiceBtn1, choiceBtn2, choiceBtn3, choiceBtn4};

        inputPanel.add(multipleChoicePanel, "multiple");

        identificationPanel.setBackground(new java.awt.Color(51, 51, 51));
        identificationPanel.setForeground(new java.awt.Color(255, 255, 255));
        identificationPanel.setPreferredSize(new java.awt.Dimension(964, 230));

        identificationInputTxtFld.setBackground(new java.awt.Color(51, 51, 51));
        identificationInputTxtFld.setFont(new java.awt.Font("JetBrains Mono", 1, 32)); // NOI18N
        identificationInputTxtFld.setForeground(new java.awt.Color(255, 255, 255));
        identificationInputTxtFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        identificationSubmitBtn.setBackground(new java.awt.Color(204, 255, 204));
        identificationSubmitBtn.setFont(new java.awt.Font("JetBrains Mono", 0, 16)); // NOI18N
        identificationSubmitBtn.setForeground(new java.awt.Color(0, 102, 204));
        identificationSubmitBtn.setText("Enter");
        identificationSubmitBtn.setBorder(null);
        identificationSubmitBtn.setBorderPainted(false);

        javax.swing.GroupLayout identificationPanelLayout = new javax.swing.GroupLayout(identificationPanel);
        identificationPanel.setLayout(identificationPanelLayout);
        identificationPanelLayout.setHorizontalGroup(
            identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identificationPanelLayout.createSequentialGroup()
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(identificationPanelLayout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(identificationSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(identificationPanelLayout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(identificationInputTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        identificationPanelLayout.setVerticalGroup(
            identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identificationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(identificationInputTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(identificationSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputPanel.add(identificationPanel, "identification");

        trueOrFalsePanel.setBackground(new java.awt.Color(51, 51, 51));
        trueOrFalsePanel.setForeground(new java.awt.Color(255, 255, 255));
        trueOrFalsePanel.setPreferredSize(new java.awt.Dimension(964, 125));
        trueOrFalsePanel.setLayout(new java.awt.GridLayout(0, 2));

        trueBtn.setBackground(new java.awt.Color(204, 255, 204));
        trueBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 32)); // NOI18N
        trueBtn.setForeground(new java.awt.Color(0, 102, 204));
        trueBtn.setText("true");
        trueBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        trueBtn.setPreferredSize(new java.awt.Dimension(200, 125));
        trueOrFalsePanel.add(trueBtn);

        falseBtn.setBackground(new java.awt.Color(204, 255, 204));
        falseBtn.setFont(new java.awt.Font("JetBrains Mono", 1, 32)); // NOI18N
        falseBtn.setForeground(new java.awt.Color(0, 102, 204));
        falseBtn.setText("false");
        falseBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        falseBtn.setPreferredSize(new java.awt.Dimension(200, 125));
        trueOrFalsePanel.add(falseBtn);

        inputPanel.add(trueOrFalsePanel, "boolean");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(361, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(320, Short.MAX_VALUE)
                    .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)))
        );

    }// </editor-fold>//GEN-END:initComponents

    // adding custom button event handler should be ran BEFORE adding own event handlers
    protected void addActionListenerToButtons(java.awt.event.ActionListener evtl) {
        for (JButton inputBtn : getAllButtons()) {
            inputBtn.addActionListener(evtl);
        }
    }

    // should be ran AFTER adding custom event handlers
    protected void addQPanelButtonActionPerformed() {
        for (JButton inputBtn : getAllButtons()) {
            inputBtn.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    choiceButtonActionPerformed(evt);
                }
            });
        };
    }

    private void choiceButtonActionPerformed(java.awt.event.ActionEvent evt) {
        JButton btn = (JButton) evt.getSource();
        if (currentQuestion.getType().equals("identification")) {
            currentChoice = identificationInputTxtFld.getText();
            identificationInputTxtFld.setText("");
        } else {
            currentChoice = unwrapStringWithHtmlTag(btn.getText());
        }

        if (currentQuestion.getType().equals("multiple")) {
            try {
                correctChoiceBtn.setBackground(btnColorCorrect);
                if (!choiceIsCorrect()) {
                    btn.setBackground(btnColorWrong);
                }
                correctChoiceBtn.repaint();
                correctChoiceBtn.revalidate();
                Thread.sleep(250);
                correctChoiceBtn.setBackground(btnColorDefault);
                btn.setBackground(btnColorDefault);
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
        }
    }

    public void setCurrentQuestion(Question q) {
        currentQuestion = q;
    }

    public boolean choiceIsCorrect() {
        return currentQuestion.isCorrect(currentChoice);
    }

    protected void displayQuestion() {
        questionLabel.setText(wrapStringWithHtmlTag(currentQuestion.getQuestion()));
        if (currentQuestion.getType().equals("multiple")) {
            correctChoiceBtn = choiceBtns[new Random().nextInt(4)];
            int wrongChoiceIndex = 0;
            for (JButton btn : choiceBtns) {
                if (btn != correctChoiceBtn) {
                    String wrongChoice = currentQuestion.getWrongChoiceAtIndex(wrongChoiceIndex);
                    btn.setText(wrapStringWithHtmlTag(wrongChoice));
                    wrongChoiceIndex++;
                }
            }
            correctChoiceBtn.setText(currentQuestion.getAnswer());
        }
        display(currentQuestion.getType());
    }

    private void display(String cardName) {
        CardLayout card = (CardLayout) inputPanel.getLayout();
        card.show(inputPanel, cardName);
    }

    // 
    private String wrapStringWithHtmlTag(String str) {
        return "<html>" + str + "</html>";
    }

    private String unwrapStringWithHtmlTag(String str) {
        return str.replace("<html>", "").replace("</html>", "");
    }

    public JButton[] getAllButtons() {
        return new JButton[]{choiceBtn1, choiceBtn2, choiceBtn3, choiceBtn4, trueBtn, falseBtn, identificationSubmitBtn};
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton choiceBtn1;
    private javax.swing.JButton choiceBtn2;
    private javax.swing.JButton choiceBtn3;
    private javax.swing.JButton choiceBtn4;
    private javax.swing.JButton falseBtn;
    private javax.swing.JTextField identificationInputTxtFld;
    private javax.swing.JPanel identificationPanel;
    private javax.swing.JButton identificationSubmitBtn;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel multipleChoicePanel;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JButton trueBtn;
    private javax.swing.JPanel trueOrFalsePanel;
    // End of variables declaration//GEN-END:variables
    private JButton correctChoiceBtn;
    private JButton[] choiceBtns;
    private static java.awt.Color btnColorDefault = new Color(204, 255, 204);
    private static java.awt.Color btnColorCorrect = new Color(118, 254, 0);
    private static java.awt.Color btnColorWrong = new Color(253, 26, 26);

}
