/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.kierjohn.testgui;

/**
 *
 * @author LENOVO
 */
public class QuestionPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuestionPanel
     */
    public QuestionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionLabel = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        multipleChoicePanel = new javax.swing.JPanel();
        choiceBtn1 = new javax.swing.JButton();
        choiceBtn2 = new javax.swing.JButton();
        choiceBtn3 = new javax.swing.JButton();
        choiceBtn4 = new javax.swing.JButton();
        identificationPanel = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        trueOrFalsePanel = new javax.swing.JPanel();
        trueBtn = new javax.swing.JButton();
        falseBtn = new javax.swing.JButton();

        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionLabel.setFocusable(false);
        questionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        inputPanel.setLayout(new java.awt.CardLayout());

        multipleChoicePanel.setLayout(new java.awt.GridLayout(2, 2));

        choiceBtn1.setPreferredSize(new java.awt.Dimension(200, 125));
        choiceBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceBtn1ActionPerformed(evt);
            }
        });
        multipleChoicePanel.add(choiceBtn1);

        choiceBtn2.setPreferredSize(new java.awt.Dimension(200, 125));
        choiceBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceBtn2ActionPerformed(evt);
            }
        });
        multipleChoicePanel.add(choiceBtn2);

        choiceBtn3.setPreferredSize(new java.awt.Dimension(200, 125));
        choiceBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceBtn3ActionPerformed(evt);
            }
        });
        multipleChoicePanel.add(choiceBtn3);

        choiceBtn4.setPreferredSize(new java.awt.Dimension(200, 125));
        choiceBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceBtn4ActionPerformed(evt);
            }
        });
        multipleChoicePanel.add(choiceBtn4);

        inputPanel.add(multipleChoicePanel, "multiple choice");

        jButton12.setText("Enter");

        javax.swing.GroupLayout identificationPanelLayout = new javax.swing.GroupLayout(identificationPanel);
        identificationPanel.setLayout(identificationPanelLayout);
        identificationPanelLayout.setHorizontalGroup(
            identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identificationPanelLayout.createSequentialGroup()
                .addGroup(identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(identificationPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(identificationPanelLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        identificationPanelLayout.setVerticalGroup(
            identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identificationPanelLayout.createSequentialGroup()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        inputPanel.add(identificationPanel, "identification");

        trueOrFalsePanel.setLayout(new java.awt.GridLayout(0, 2));

        trueBtn.setText("True");
        trueBtn.setPreferredSize(new java.awt.Dimension(200, 125));
        trueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trueBtnActionPerformed(evt);
            }
        });
        trueOrFalsePanel.add(trueBtn);

        falseBtn.setText("False");
        falseBtn.setPreferredSize(new java.awt.Dimension(200, 125));
        falseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                falseBtnActionPerformed(evt);
            }
        });
        trueOrFalsePanel.add(falseBtn);

        inputPanel.add(trueOrFalsePanel, "boolean");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(218, Short.MAX_VALUE)
                    .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void choiceBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choiceBtn1ActionPerformed

    private void choiceBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choiceBtn2ActionPerformed

    private void choiceBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choiceBtn3ActionPerformed

    private void choiceBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choiceBtn4ActionPerformed

    private void trueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trueBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trueBtnActionPerformed

    private void falseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_falseBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_falseBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton choiceBtn1;
    private javax.swing.JButton choiceBtn2;
    private javax.swing.JButton choiceBtn3;
    private javax.swing.JButton choiceBtn4;
    private javax.swing.JButton falseBtn;
    private javax.swing.JPanel identificationPanel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JButton jButton12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel multipleChoicePanel;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JButton trueBtn;
    private javax.swing.JPanel trueOrFalsePanel;
    // End of variables declaration//GEN-END:variables
}
