/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.kierjohn.testgui;

import java.awt.*;
import java.util.Random;
import javax.swing.*;
import javax.swing.text.*;
import java.time.*;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author LENOVO /**
 *
 * @author LENOVO
 */
public class QuizPanel extends javax.swing.JPanel {

    private Question currentQuestion;
    String currentChoice;
    Timer timer;

    /**
     * Creates new form QuestionPanel
     */
    public QuizPanel() {
        initComponents();
        timer = new Timer(1500, (java.awt.event.ActionEvent evt) -> {
            if (choiceIsCorrect()) {
                currentScore += 10;
                correctAnswerCount++;
                System.out.println("corr");
            }
            if (isFinished = index == currentQuiz.getQCount()) {
                displayFinish();
            } else {
                currentQuestion = currentQuiz.getQuestionAtIndex(index);
                displayCurrentQuestion();
            }
            resetInputComponents();
        });
        timer.setRepeats(false);
    }

    private void startTimer() {
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quizGamePanel = new javax.swing.JPanel();
        qPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        questionText = new javax.swing.JTextPane();
        categoryLabel = new javax.swing.JLabel();
        difficultyLabel = new javax.swing.JLabel();
        scoreLiteralLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        questionsLiteralLabel = new javax.swing.JLabel();
        questionCounterLabel = new javax.swing.JLabel();
        quizInfoLabel = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        multipleChoicePanel = new javax.swing.JPanel();
        choiceBtn1 = new javax.swing.JButton();
        choiceBtn2 = new javax.swing.JButton();
        choiceBtn3 = new javax.swing.JButton();
        choiceBtn4 = new javax.swing.JButton();
        trueOrFalsePanel = new javax.swing.JPanel();
        trueBtn = new javax.swing.JButton();
        falseBtn = new javax.swing.JButton();
        identificationPanel = new javax.swing.JPanel();
        identificationInputTxtFld = new javax.swing.JTextField();
        quizFinishedPanel = new javax.swing.JPanel();
        quizResultLabel = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        resultScoreCountLabel = new javax.swing.JLabel();
        resultCorrectAnswersLabel = new javax.swing.JLabel();
        playGameBtn1 = new javax.swing.JButton();
        saveAsReviewerBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(106, 49, 144));
        setPreferredSize(new java.awt.Dimension(1280, 620));
        setLayout(new java.awt.CardLayout());

        quizGamePanel.setBackground(new java.awt.Color(106, 49, 144));
        quizGamePanel.setPreferredSize(new java.awt.Dimension(1280, 620));

        qPanel.setBackground(new java.awt.Color(29, 20, 101));

        jScrollPane2.setBorder(null);
        jScrollPane2.setFocusable(false);
        jScrollPane2.setRequestFocusEnabled(false);
        jScrollPane2.setVerifyInputWhenFocusTarget(false);

        questionText.setEditable(false);
        questionText.setBackground(new java.awt.Color(29, 20, 101));
        questionText.setBorder(null);
        questionText.setFont(GlobalUtils.getFont(1, 40)
        );
        questionText.setForeground(new java.awt.Color(249, 193, 5));
        questionText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        questionText.setFocusCycleRoot(false);
        questionText.setFocusable(false);
        questionText.setRequestFocusEnabled(false);
        questionText.setVerifyInputWhenFocusTarget(false);
        StyledDocument doc = questionText.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
        jScrollPane2.setViewportView(questionText);

        categoryLabel.setBackground(new java.awt.Color(0, 51, 51));
        categoryLabel.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 16)
        );
        categoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        categoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoryLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        categoryLabel.setPreferredSize(new java.awt.Dimension(1, 16));

        difficultyLabel.setBackground(new java.awt.Color(0, 51, 51));
        difficultyLabel.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 16)
        );
        difficultyLabel.setForeground(new java.awt.Color(255, 255, 255));
        difficultyLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        difficultyLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        difficultyLabel.setPreferredSize(new java.awt.Dimension(1, 16));

        scoreLiteralLabel.setBackground(new java.awt.Color(0, 51, 51));
        scoreLiteralLabel.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 20)
        );
        scoreLiteralLabel.setForeground(new java.awt.Color(255, 255, 255));
        scoreLiteralLabel.setText("Score");

        scoreLabel.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 20)
        );
        scoreLabel.setForeground(new java.awt.Color(255, 255, 255));
        scoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        scoreLabel.setText("0");

        questionsLiteralLabel.setBackground(new java.awt.Color(0, 51, 51));
        questionsLiteralLabel.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 20)
        );
        questionsLiteralLabel.setForeground(new java.awt.Color(255, 255, 255));
        questionsLiteralLabel.setText("Questions");
        questionsLiteralLabel.setFocusable(false);

        questionCounterLabel.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 20)
        );
        questionCounterLabel.setForeground(new java.awt.Color(255, 255, 255));
        questionCounterLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        questionCounterLabel.setText(" ");

        quizInfoLabel.setBackground(new java.awt.Color(0, 51, 51));
        quizInfoLabel.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 20)
        );
        quizInfoLabel.setForeground(new java.awt.Color(255, 255, 255));
        quizInfoLabel.setText(" ");
        quizInfoLabel.setFocusable(false);

        addQPanelButtonActionPerformed();

        javax.swing.GroupLayout qPanelLayout = new javax.swing.GroupLayout(qPanel);
        qPanel.setLayout(qPanelLayout);
        qPanelLayout.setHorizontalGroup(
            qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(quizInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(difficultyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(497, 497, 497)
                .addGroup(qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(questionsLiteralLabel)
                    .addComponent(questionCounterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scoreLiteralLabel)
                    .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        qPanelLayout.setVerticalGroup(
            qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qPanelLayout.createSequentialGroup()
                .addGroup(qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(qPanelLayout.createSequentialGroup()
                                .addGroup(qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(questionsLiteralLabel)
                                    .addComponent(scoreLiteralLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(scoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                    .addComponent(questionCounterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(qPanelLayout.createSequentialGroup()
                                .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(difficultyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(qPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(quizInfoLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        inputPanel.setBackground(new java.awt.Color(51, 51, 51));
        inputPanel.setForeground(new java.awt.Color(255, 255, 255));
        inputPanel.setOpaque(false);
        inputPanel.setPreferredSize(new java.awt.Dimension(1280, 300));
        inputPanel.setRequestFocusEnabled(false);
        inputPanel.setLayout(new java.awt.CardLayout());

        multipleChoicePanel.setBackground(new java.awt.Color(106, 49, 144));
        multipleChoicePanel.setForeground(new java.awt.Color(255, 255, 255));
        multipleChoicePanel.setAutoscrolls(true);
        multipleChoicePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        multipleChoicePanel.setPreferredSize(new java.awt.Dimension(964, 300));
        multipleChoicePanel.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        choiceBtn1.setBackground(DEFAULT_COLOR);
        choiceBtn1.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 25)
        );
        choiceBtn1.setForeground(new java.awt.Color(29, 20, 101));
        choiceBtn1.setBorder(null);
        choiceBtn1.setBorderPainted(false);
        choiceBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choiceBtn1.setDefaultCapable(false);
        choiceBtn1.setFocusPainted(false);
        choiceBtn1.setFocusable(false);
        choiceBtn1.setOpaque(true);
        choiceBtn1.setPreferredSize(new java.awt.Dimension(200, 125));
        choiceBtn1.setRequestFocusEnabled(false);
        choiceBtn1.setRolloverEnabled(false);
        choiceBtn1.setVerifyInputWhenFocusTarget(false);
        multipleChoicePanel.add(choiceBtn1);

        choiceBtn2.setBackground(DEFAULT_COLOR);
        choiceBtn2.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 25)
        );
        choiceBtn2.setForeground(new java.awt.Color(29, 20, 101));
        choiceBtn2.setBorder(null);
        choiceBtn2.setBorderPainted(false);
        choiceBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choiceBtn2.setDefaultCapable(false);
        choiceBtn2.setFocusPainted(false);
        choiceBtn2.setFocusable(false);
        choiceBtn2.setOpaque(true);
        choiceBtn2.setPreferredSize(new java.awt.Dimension(200, 125));
        choiceBtn2.setRequestFocusEnabled(false);
        choiceBtn2.setRolloverEnabled(false);
        choiceBtn2.setVerifyInputWhenFocusTarget(false);
        multipleChoicePanel.add(choiceBtn2);

        choiceBtn3.setBackground(DEFAULT_COLOR);
        choiceBtn3.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 25)
        );
        choiceBtn3.setForeground(new java.awt.Color(29, 20, 101));
        choiceBtn3.setBorder(null);
        choiceBtn3.setBorderPainted(false);
        choiceBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choiceBtn3.setDefaultCapable(false);
        choiceBtn3.setFocusPainted(false);
        choiceBtn3.setFocusable(false);
        choiceBtn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        choiceBtn3.setOpaque(true);
        choiceBtn3.setPreferredSize(new java.awt.Dimension(200, 125));
        choiceBtn3.setRequestFocusEnabled(false);
        choiceBtn3.setRolloverEnabled(false);
        choiceBtn3.setVerifyInputWhenFocusTarget(false);
        multipleChoicePanel.add(choiceBtn3);

        choiceBtn4.setBackground(DEFAULT_COLOR);
        choiceBtn4.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 25)
        );
        choiceBtn4.setForeground(new java.awt.Color(29, 20, 101));
        choiceBtn4.setBorder(null);
        choiceBtn4.setBorderPainted(false);
        choiceBtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choiceBtn4.setDefaultCapable(false);
        choiceBtn4.setFocusPainted(false);
        choiceBtn4.setFocusable(false);
        choiceBtn4.setOpaque(true);
        choiceBtn4.setPreferredSize(new java.awt.Dimension(200, 125));
        choiceBtn4.setRequestFocusEnabled(false);
        choiceBtn4.setRolloverEnabled(false);
        choiceBtn4.setVerifyInputWhenFocusTarget(false);
        multipleChoicePanel.add(choiceBtn4);

        inputBtns = new JButton[] {choiceBtn1, choiceBtn2, choiceBtn3, choiceBtn4};

        inputPanel.add(multipleChoicePanel, "multiple");

        trueOrFalsePanel.setBackground(new java.awt.Color(106, 49, 144));
        trueOrFalsePanel.setForeground(new java.awt.Color(255, 255, 255));
        trueOrFalsePanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        trueOrFalsePanel.setLayout(new java.awt.GridLayout(0, 2, 5, 0));

        trueBtn.setBackground(DEFAULT_COLOR);
        trueBtn.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 50)
        );
        trueBtn.setForeground(new java.awt.Color(29, 20, 101));
        trueBtn.setText("true");
        trueBtn.setBorder(null);
        trueBtn.setBorderPainted(false);
        trueBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trueBtn.setDefaultCapable(false);
        trueBtn.setFocusPainted(false);
        trueBtn.setFocusable(false);
        trueBtn.setPreferredSize(new java.awt.Dimension(200, 125));
        trueBtn.setRequestFocusEnabled(false);
        trueBtn.setRolloverEnabled(false);
        trueBtn.setVerifyInputWhenFocusTarget(false);
        trueOrFalsePanel.add(trueBtn);

        falseBtn.setBackground(DEFAULT_COLOR);
        falseBtn.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 50)
        );
        falseBtn.setForeground(new java.awt.Color(29, 20, 101));
        falseBtn.setText("false");
        falseBtn.setBorder(null);
        falseBtn.setBorderPainted(false);
        falseBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        falseBtn.setDefaultCapable(false);
        falseBtn.setFocusPainted(false);
        falseBtn.setFocusable(false);
        falseBtn.setPreferredSize(new java.awt.Dimension(200, 125));
        falseBtn.setRequestFocusEnabled(false);
        falseBtn.setRolloverEnabled(false);
        falseBtn.setVerifyInputWhenFocusTarget(false);
        trueOrFalsePanel.add(falseBtn);
        falseBtn.getAccessibleContext().setAccessibleName("");

        inputPanel.add(trueOrFalsePanel, "boolean");

        identificationPanel.setBackground(new java.awt.Color(106, 49, 144));
        identificationPanel.setForeground(new java.awt.Color(255, 255, 255));
        identificationPanel.setPreferredSize(new java.awt.Dimension(1280, 720));

        identificationInputTxtFld.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 32)
        );
        identificationInputTxtFld.setForeground(new java.awt.Color(29, 20, 101));
        identificationInputTxtFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout identificationPanelLayout = new javax.swing.GroupLayout(identificationPanel);
        identificationPanel.setLayout(identificationPanelLayout);
        identificationPanelLayout.setHorizontalGroup(
            identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identificationPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(identificationInputTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        identificationPanelLayout.setVerticalGroup(
            identificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identificationPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(identificationInputTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputPanel.add(identificationPanel, "identification");

        javax.swing.GroupLayout quizGamePanelLayout = new javax.swing.GroupLayout(quizGamePanel);
        quizGamePanel.setLayout(quizGamePanelLayout);
        quizGamePanelLayout.setHorizontalGroup(
            quizGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(quizGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(quizGamePanelLayout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1093, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(94, Short.MAX_VALUE)))
            .addGroup(quizGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(quizGamePanelLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(qPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );
        quizGamePanelLayout.setVerticalGroup(
            quizGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(quizGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quizGamePanelLayout.createSequentialGroup()
                    .addContainerGap(311, Short.MAX_VALUE)
                    .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22)))
            .addGroup(quizGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(quizGamePanelLayout.createSequentialGroup()
                    .addComponent(qPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 313, Short.MAX_VALUE)))
        );

        add(quizGamePanel, "quiz game card");

        quizFinishedPanel.setBackground(new java.awt.Color(106, 49, 144));
        quizFinishedPanel.setPreferredSize(new java.awt.Dimension(1280, 645));

        quizResultLabel.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 50)
        );
        quizResultLabel.setForeground(new java.awt.Color(240, 240, 240));
        quizResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizResultLabel.setText("Result:");

        jLabel111.setBackground(new java.awt.Color(0, 51, 51));
        jLabel111.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 25)
        );
        jLabel111.setForeground(new java.awt.Color(255, 255, 255));
        jLabel111.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel111.setText("Total Score:");

        jLabel112.setBackground(new java.awt.Color(0, 51, 51));
        jLabel112.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 25)
        );
        jLabel112.setForeground(new java.awt.Color(255, 255, 255));
        jLabel112.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel112.setText("Correct Answers:");

        resultScoreCountLabel.setBackground(new java.awt.Color(0, 51, 51));
        resultScoreCountLabel.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 25)
        );
        resultScoreCountLabel.setForeground(new java.awt.Color(255, 255, 255));

        resultCorrectAnswersLabel.setBackground(new java.awt.Color(0, 51, 51));
        resultCorrectAnswersLabel.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 25)
        );
        resultCorrectAnswersLabel.setForeground(new java.awt.Color(255, 255, 255));

        playGameBtn1.setBackground(GlobalUtils.DEFAULT_BUTTON_COLOR);
        playGameBtn1.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 25)
        );
        playGameBtn1.setText("New Game");
        playGameBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playGameBtn1.setDefaultCapable(false);
        playGameBtn1.setFocusable(false);
        playGameBtn1.setName("playQuizBtn"); // NOI18N
        playGameBtn1.setPreferredSize(new java.awt.Dimension(128, 32));
        playGameBtn1.setRequestFocusEnabled(false);
        playGameBtn1.setRolloverEnabled(false);
        playGameBtn1.setVerifyInputWhenFocusTarget(false);
        playGameBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playGameBtn1ActionPerformed(evt);
            }
        });

        saveAsReviewerBtn.setBackground(GlobalUtils.DEFAULT_BUTTON_COLOR);
        saveAsReviewerBtn.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 16));
        saveAsReviewerBtn.setText("Save As Reviewer");
        saveAsReviewerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveAsReviewerBtn.setDefaultCapable(false);
        saveAsReviewerBtn.setFocusable(false);
        saveAsReviewerBtn.setName("playQuizBtn"); // NOI18N
        saveAsReviewerBtn.setPreferredSize(new java.awt.Dimension(128, 32));
        saveAsReviewerBtn.setRequestFocusEnabled(false);
        saveAsReviewerBtn.setRolloverEnabled(false);
        saveAsReviewerBtn.setVerifyInputWhenFocusTarget(false);
        saveAsReviewerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsReviewerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout quizFinishedPanelLayout = new javax.swing.GroupLayout(quizFinishedPanel);
        quizFinishedPanel.setLayout(quizFinishedPanelLayout);
        quizFinishedPanelLayout.setHorizontalGroup(
            quizFinishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizFinishedPanelLayout.createSequentialGroup()
                .addGap(496, 496, 496)
                .addGroup(quizFinishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel112, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jLabel111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(quizFinishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultScoreCountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(resultCorrectAnswersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(455, 455, 455))
            .addGroup(quizFinishedPanelLayout.createSequentialGroup()
                .addGroup(quizFinishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quizFinishedPanelLayout.createSequentialGroup()
                        .addGap(462, 462, 462)
                        .addComponent(quizResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(quizFinishedPanelLayout.createSequentialGroup()
                        .addGap(546, 546, 546)
                        .addGroup(quizFinishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveAsReviewerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playGameBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        quizFinishedPanelLayout.setVerticalGroup(
            quizFinishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizFinishedPanelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(quizResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(77, 77, 77)
                .addGroup(quizFinishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resultCorrectAnswersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel112, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(quizFinishedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resultScoreCountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82)
                .addComponent(playGameBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveAsReviewerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        add(quizFinishedPanel, "quiz finished card");
        quizFinishedPanel.getAccessibleContext().setAccessibleName("quizFinished");
    }// </editor-fold>//GEN-END:initComponents

    private void playGameBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playGameBtn1ActionPerformed
        MainFrame.FRAME.gotoQuizGameSetupPanel();
    }//GEN-LAST:event_playGameBtn1ActionPerformed

    private void saveAsReviewerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsReviewerBtnActionPerformed
        String fileName = "Reviewer " + DateTimeFormatter.ofPattern("uuuu-MM-dd HH-mm-ss").format(LocalDateTime.now());
        currentQuiz.setName(fileName);
        GlobalUtils.writeQuizToChosenFile(currentQuiz);
    }//GEN-LAST:event_saveAsReviewerBtnActionPerformed

//    // adding custom button event handler should be ran BEFORE adding own event handlers
//    protected void addActionListenerToInput(java.awt.event.ActionListener evtl) {
//        for (JButton inputBtn : getAllButtons()) {
//            inputBtn.addActionListener(evtl);
//        }
//        identificationInputTxtFld.addActionListener(evtl);
//    }

    // should be ran AFTER adding custom event handlers
    private void addQPanelButtonActionPerformed() {
        for (JButton inputBtn : getAllButtons()) {
            inputBtn.addActionListener((java.awt.event.ActionEvent evt) -> {
                choiceButtonActionPerformed(evt);
            });
        }
        identificationInputTxtFld.addActionListener((java.awt.event.ActionEvent evt) -> {
            choiceButtonActionPerformed(evt);
        });
    }

    protected void startQuiz(Quiz quiz, String type) {
        Question sampleQ = quiz.getQuestionAtIndex(0);
        String infoDisplay;
        if (type.equals("api")) {
            infoDisplay = "<html>" + sampleQ.getCategory() + "<br>" + sampleQ.getDifficulty().toUpperCase();
            saveAsReviewerBtn.setVisible(true);
        } else {
            infoDisplay = quiz.getName();
            saveAsReviewerBtn.setVisible(false);
        }
        displayCard(this, "quiz game card");
        quizInfoLabel.setText(infoDisplay);
        currentQuiz = quiz;
        index = currentScore = correctAnswerCount = 0;
        isFinished = false;
        questionCounterLabel.setText(index + 1 + "/" + currentQuiz.getQCount());
        currentQuestion = currentQuiz.getQuestionAtIndex(index);
        displayCurrentQuestion();
    }

    private void displayFinish() {
        resultCorrectAnswersLabel.setText(correctAnswerCount + " / " + currentQuiz.getQCount());
        resultScoreCountLabel.setText(currentScore + "");
        displayCard(this, "quiz finished card");
    }

    private void choiceButtonActionPerformed(java.awt.event.ActionEvent evt) {
        inputComponent = (JComponent) evt.getSource();
        if (currentQuestion.getType().equals("identification")) {
            currentChoice = identificationInputTxtFld.getText();
            identificationInputTxtFld.setEnabled(false);
        } else {
            for (JButton btn : getAllButtons()) {
                btn.setEnabled(false);
            }
            if (currentQuestion.getType().equals("boolean")) {
                correctChoiceBtn = (currentQuestion.isCorrect("true")) ? trueBtn : falseBtn;
            }
            currentChoice = ((JButton) inputComponent).getText();
            correctChoiceBtn.setBackground(CORRECT_COLOR);
        }
        startTimer();
        inputComponent.setBackground((choiceIsCorrect()) ? CORRECT_COLOR : WRONG_COLOR);
        index++;
    }

    private void resetInputComponents() {
        identificationInputTxtFld.setBackground(Color.WHITE);
        identificationInputTxtFld.setEnabled(true);
        for (JButton button : getAllButtons()) {
            button.setEnabled(true);
            button.setBackground(DEFAULT_COLOR);
        }
    }

    protected void setCurrentQuestion(Question q) {
        currentQuestion = q;
    }

    protected boolean choiceIsCorrect() {
        return currentQuestion.isCorrect(currentChoice);
    }

    private void displayCurrentQuestion() {
        questionCounterLabel.setText(index + 1 + "/" + currentQuiz.getQCount());
        scoreLabel.setText(currentScore + "");
        questionText.setText(currentQuestion.getQuestion());
        identificationInputTxtFld.setText("");
        if (currentQuestion.getType().equals("multiple")) {
            correctChoiceBtn = inputBtns[new Random().nextInt(4)];
            int wrongChoiceIndex = 0;
            for (JButton btn : inputBtns) {
                if (btn != correctChoiceBtn) {
                    String wrongChoice = currentQuestion.getWrongChoiceAtIndex(wrongChoiceIndex);
                    btn.setText(wrongChoice);
                    wrongChoiceIndex++;
                }
            }
            correctChoiceBtn.setText(currentQuestion.getAnswer());
        }
        displayCard(inputPanel, currentQuestion.getType());
    }

    private void displayCard(Container container, String cardName) {
        CardLayout card = (CardLayout) container.getLayout();
        card.show(container, cardName);
    }

    protected JButton[] getAllButtons() {
        return new JButton[]{choiceBtn1, choiceBtn2, choiceBtn3, choiceBtn4, trueBtn, falseBtn};
    }

    private void quizDisplayScoreAndCounter(boolean bool) {
        questionsLiteralLabel.setVisible(bool);
        questionCounterLabel.setVisible(bool);
        scoreLiteralLabel.setVisible(bool);
        scoreLabel.setVisible(bool);
    }

    private void quizDisplayDifficultyAndCategory(boolean bool) {
        difficultyLabel.setVisible(bool);
        categoryLabel.setVisible(bool);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JButton choiceBtn1;
    private javax.swing.JButton choiceBtn2;
    private javax.swing.JButton choiceBtn3;
    private javax.swing.JButton choiceBtn4;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JButton falseBtn;
    private javax.swing.JTextField identificationInputTxtFld;
    private javax.swing.JPanel identificationPanel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel multipleChoicePanel;
    protected javax.swing.JButton playGameBtn1;
    private javax.swing.JPanel qPanel;
    protected javax.swing.JLabel questionCounterLabel;
    private javax.swing.JTextPane questionText;
    private javax.swing.JLabel questionsLiteralLabel;
    private javax.swing.JPanel quizFinishedPanel;
    private javax.swing.JPanel quizGamePanel;
    private javax.swing.JLabel quizInfoLabel;
    private javax.swing.JLabel quizResultLabel;
    private javax.swing.JLabel resultCorrectAnswersLabel;
    private javax.swing.JLabel resultScoreCountLabel;
    protected javax.swing.JButton saveAsReviewerBtn;
    protected javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel scoreLiteralLabel;
    private javax.swing.JButton trueBtn;
    private javax.swing.JPanel trueOrFalsePanel;
    // End of variables declaration//GEN-END:variables
    private JButton correctChoiceBtn;
    private JButton[] inputBtns;
    protected static final java.awt.Color DEFAULT_COLOR = new Color(255, 255, 255);
    protected static final java.awt.Color CORRECT_COLOR = new Color(164, 252, 88);
    protected static final java.awt.Color WRONG_COLOR = new Color(253, 26, 26);
    private JComponent inputComponent;
    private int currentScore;
    private int correctAnswerCount;
    private Quiz currentQuiz;
    private int index;
    protected boolean isFinished = true;
    private String type;

}
