/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.kierjohn.testgui;

import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;

/**
 *
 * @author LENOVO
 */
public class ReviewerEditorPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReviewerCreationPanel
     */
    public ReviewerEditorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlsPanel = new javax.swing.JPanel();
        saveReviewerBtn = new javax.swing.JButton();
        questionFormCount = new javax.swing.JLabel();
        clearFormBtn = new javax.swing.JButton();
        addQuestionForm1 = new javax.swing.JButton();
        qCountLiteralLabel = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        questionFormContainerPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(106, 49, 144));
        setPreferredSize(new java.awt.Dimension(1280, 645));

        controlsPanel.setBackground(new java.awt.Color(106, 49, 144));

        saveReviewerBtn.setBackground(new java.awt.Color(204,255,204));
        saveReviewerBtn.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 16)); // NOI18N
        saveReviewerBtn.setText("Save Quiz");
        saveReviewerBtn.setBorder(null);
        saveReviewerBtn.setBorderPainted(false);
        saveReviewerBtn.setDefaultCapable(false);
        saveReviewerBtn.setFocusPainted(false);
        saveReviewerBtn.setFocusable(false);
        saveReviewerBtn.setName("playQuizBtn"); // NOI18N
        saveReviewerBtn.setPreferredSize(new java.awt.Dimension(128, 32));
        saveReviewerBtn.setRequestFocusEnabled(false);
        saveReviewerBtn.setRolloverEnabled(false);
        saveReviewerBtn.setVerifyInputWhenFocusTarget(false);
        saveReviewerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveReviewerBtnActionPerformed(evt);
            }
        });

        questionFormCount.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 16)); // NOI18N
        questionFormCount.setForeground(new java.awt.Color(250, 242, 249));
        questionFormCount.setText("0");

        clearFormBtn.setBackground(new java.awt.Color(204,255,204));
        clearFormBtn.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 16)); // NOI18N
        clearFormBtn.setText("Clear Form");
        clearFormBtn.setBorder(null);
        clearFormBtn.setBorderPainted(false);
        clearFormBtn.setDefaultCapable(false);
        clearFormBtn.setFocusPainted(false);
        clearFormBtn.setFocusable(false);
        clearFormBtn.setName("playQuizBtn"); // NOI18N
        clearFormBtn.setPreferredSize(new java.awt.Dimension(128, 32));
        clearFormBtn.setRequestFocusEnabled(false);
        clearFormBtn.setRolloverEnabled(false);
        clearFormBtn.setVerifyInputWhenFocusTarget(false);
        clearFormBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFormBtnActionPerformed(evt);
            }
        });

        addQuestionForm1.setBackground(new java.awt.Color(204,255,204));
        addQuestionForm1.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 16)); // NOI18N
        addQuestionForm1.setText("Add Question");
        addQuestionForm1.setBorder(null);
        addQuestionForm1.setBorderPainted(false);
        addQuestionForm1.setDefaultCapable(false);
        addQuestionForm1.setFocusPainted(false);
        addQuestionForm1.setFocusable(false);
        addQuestionForm1.setName("playQuizBtn"); // NOI18N
        addQuestionForm1.setPreferredSize(new java.awt.Dimension(128, 32));
        addQuestionForm1.setRequestFocusEnabled(false);
        addQuestionForm1.setRolloverEnabled(false);
        addQuestionForm1.setVerifyInputWhenFocusTarget(false);
        addQuestionForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuestionForm1ActionPerformed(evt);
            }
        });

        qCountLiteralLabel.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 16)); // NOI18N
        qCountLiteralLabel.setForeground(new java.awt.Color(250, 242, 249));
        qCountLiteralLabel.setText("Question Count:");

        javax.swing.GroupLayout controlsPanelLayout = new javax.swing.GroupLayout(controlsPanel);
        controlsPanel.setLayout(controlsPanelLayout);
        controlsPanelLayout.setHorizontalGroup(
            controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveReviewerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addQuestionForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearFormBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qCountLiteralLabel)
                    .addComponent(questionFormCount))
                .addContainerGap())
        );
        controlsPanelLayout.setVerticalGroup(
            controlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addQuestionForm1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(clearFormBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveReviewerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(qCountLiteralLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionFormCount)
                .addContainerGap())
        );

        jScrollPane.setBorder(null);
        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane.setMinimumSize(new java.awt.Dimension(0, 0));
        jScrollPane.setViewportView(questionFormContainerPanel);
        jScrollPane.getVerticalScrollBar().setUnitIncrement(16);

        questionFormContainerPanel.setBackground(new java.awt.Color(106, 49, 144));
        questionFormContainerPanel.setFocusable(false);
        questionFormContainerPanel.setRequestFocusEnabled(false);
        questionFormContainerPanel.setVerifyInputWhenFocusTarget(false);
        questionFormContainerPanel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                questionFormContainerPanelComponentRemoved(evt);
            }
        });
        questionFormContainerPanel.setLayout(new java.awt.GridLayout(0, 1, 8, 0));
        jScrollPane.setViewportView(questionFormContainerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(913, Short.MAX_VALUE)
                .addComponent(controlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(292, 292, 292)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(387, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(controlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(356, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clearFormBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFormBtnActionPerformed
        questionFormContainerPanel.removeAll();
        questionFormContainerPanel.revalidate();
        questionFormContainerPanel.repaint();
        questionFormCount.setText("0");
    }//GEN-LAST:event_clearFormBtnActionPerformed

    private void addQuestionForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuestionForm1ActionPerformed
        int index = formCount();
        QuizQuestionForm qForm = new QuizQuestionForm(questionFormContainerPanel);
        
        qForm.deleteBtn.addActionListener((java.awt.event.ActionEvent evt1) -> {
            deletedFormActionPerformed(evt1);
        });
        
        qForm.setIndex(index);
        questionFormContainerPanel.add(qForm);
        questionFormContainerPanel.revalidate();
        questionFormContainerPanel.repaint();
        questionFormCount.setText(index + "");
    }//GEN-LAST:event_addQuestionForm1ActionPerformed

    private int formCount() {
        return questionFormContainerPanel.getComponentCount();
    }
    
    private void saveReviewerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveReviewerBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                file.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(ReviewerEditorPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        quiz.outputToFile(new java.io.File("output/a.json"));
    }//GEN-LAST:event_saveReviewerBtnActionPerformed

    protected void deletedFormActionPerformed(java.awt.event.ActionEvent evt) {
        JButton deletedBtn = (JButton) evt.getSource();
        QuizQuestionForm deletedForm = (QuizQuestionForm) deletedBtn.getParent().getParent().getParent();
        int delIndex = deletedForm.getIndex();
        for (int i = delIndex; i < formCount(); i++) {
            QuizQuestionForm qForm = (QuizQuestionForm) questionFormContainerPanel.getComponent(i);
            qForm.setIndex(i-1);
        }
    }
    private void questionFormContainerPanelComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_questionFormContainerPanelComponentRemoved

    }//GEN-LAST:event_questionFormContainerPanelComponentRemoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addQuestionForm1;
    private javax.swing.JButton clearFormBtn;
    private javax.swing.JPanel controlsPanel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel qCountLiteralLabel;
    private javax.swing.JPanel questionFormContainerPanel;
    private javax.swing.JLabel questionFormCount;
    private javax.swing.JButton saveReviewerBtn;
    // End of variables declaration//GEN-END:variables
    private Quiz quiz;
    private int lastIndex;
}