/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.kierjohn.testgui;

import java.awt.*;

/**
 *
 * @author LENOVO
 */
public class ReviewerQuestionForm extends javax.swing.JPanel {
    private final java.awt.Container parent;
    /**
     * Creates new form QuizQuestionForm
     * @param parent
     */
    public ReviewerQuestionForm(Container parent) {
        initComponents();
        this.parent = parent;
    }
    
    public ReviewerQuestionForm(Container parent, Question q) {
        this(parent);
        questionTextField.setText(q.getQuestion());
        int index = 0;
        switch (q.getType()) {
            case "multiple" -> {
                multipleCorrectAnswer.setText(q.getAnswer());
                wrongChoiceTextField1.setText(q.getWrongChoiceAtIndex(0));
                wrongChoiceTextField2.setText(q.getWrongChoiceAtIndex(1));
                wrongChoiceTextField3.setText(q.getWrongChoiceAtIndex(2));
                index = 0;
            }
            case "boolean" -> {
                (q.getAnswer().equals("true") ? trueToggleBtn : falseToggleBtn).setSelected(true);
                index = 1;
            } case "identification" -> {
                identificationAnswerTxtField.setText(q.getAnswer());
                index = 2;
            }
        }
        qTypeInput.setSelectedIndex(index);
        CardLayout card = (CardLayout) bottonFormPanelContainer.getLayout();
        card.show(bottonFormPanelContainer, q.getType());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        formPanel = new javax.swing.JPanel();
        upperFormPanel = new javax.swing.JPanel();
        qTypeInput = new javax.swing.JComboBox<>();
        questionTextField = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        indexLabel = new javax.swing.JLabel();
        bottonFormPanelContainer = new javax.swing.JPanel();
        multipleChoiceFormPanel = new javax.swing.JPanel();
        multipleCorrectAnswer = new javax.swing.JTextField();
        wrongChoiceTextField1 = new javax.swing.JTextField();
        wrongChoiceTextField2 = new javax.swing.JTextField();
        wrongChoiceTextField3 = new javax.swing.JTextField();
        trueOrFalseFormPanel = new javax.swing.JPanel();
        defaultBooleanLabel1 = new javax.swing.JPanel();
        trueToggleBtn = new javax.swing.JToggleButton();
        falseToggleBtn = new javax.swing.JToggleButton();
        correctAnswerLabe2 = new javax.swing.JLabel();
        identificationFormPanel = new javax.swing.JPanel();
        identificationAnswerTxtField = new javax.swing.JTextField();
        barrier = new javax.swing.JPanel();

        setBackground(new java.awt.Color(106, 49, 144));
        setOpaque(false);
        setRequestFocusEnabled(false);

        formPanel.setBackground(new java.awt.Color(106, 49, 144));
        formPanel.setLayout(new java.awt.GridBagLayout());

        upperFormPanel.setBackground(new java.awt.Color(106, 49, 144));

        qTypeInput.setBackground(new Color(255, 255, 255));
        qTypeInput.setFont(com.kierjohn.testgui.GlobalUtils.getFont(0, 16));
        qTypeInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Multiple Choice", "True or False", "Identification" }));
        qTypeInput.setToolTipText("");
        qTypeInput.setName("qDiff"); // NOI18N
        qTypeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qTypeInputActionPerformed(evt);
            }
        });

        questionTextField.setBackground(new java.awt.Color(204, 204, 204));
        questionTextField.setFont(com.kierjohn.testgui.GlobalUtils.getFont(0, 16));
        questionTextField.setForeground(new java.awt.Color(51, 51, 51));
        questionTextField.setText("Question");

        deleteBtn.setBackground(new Color(255, 255, 255));
        deleteBtn.setFont(com.kierjohn.testgui.GlobalUtils.getFont(0, 16));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        titleLabel.setFont(com.kierjohn.testgui.GlobalUtils.getFont(1, 20));
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Question #");

        indexLabel.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 16)); // NOI18N
        indexLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout upperFormPanelLayout = new javax.swing.GroupLayout(upperFormPanel);
        upperFormPanel.setLayout(upperFormPanelLayout);
        upperFormPanelLayout.setHorizontalGroup(
            upperFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upperFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(upperFormPanelLayout.createSequentialGroup()
                        .addComponent(qTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(indexLabel)
                        .addGap(95, 95, 95)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(questionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        upperFormPanelLayout.setVerticalGroup(
            upperFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperFormPanelLayout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(upperFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn)
                    .addComponent(titleLabel)
                    .addComponent(indexLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(questionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        formPanel.add(upperFormPanel, gridBagConstraints);

        bottonFormPanelContainer.setBackground(new java.awt.Color(51, 51, 51));
        bottonFormPanelContainer.setLayout(new java.awt.CardLayout());

        multipleChoiceFormPanel.setBackground(new java.awt.Color(106, 49, 144));
        multipleChoiceFormPanel.setPreferredSize(new java.awt.Dimension(600, 218));

        multipleCorrectAnswer.setBackground(QuizPanel.CORRECT_COLOR);
        multipleCorrectAnswer.setFont(com.kierjohn.testgui.GlobalUtils.getFont(0, 16));
        multipleCorrectAnswer.setForeground(new java.awt.Color(51, 0, 102));
        multipleCorrectAnswer.setText("Correct Answer");
        multipleCorrectAnswer.setPreferredSize(new java.awt.Dimension(64, 32));

        wrongChoiceTextField1.setBackground(QuizPanel.WRONG_COLOR);
        wrongChoiceTextField1.setFont(com.kierjohn.testgui.GlobalUtils.getFont(0, 16));
        wrongChoiceTextField1.setForeground(new java.awt.Color(255, 255, 153));
        wrongChoiceTextField1.setText("Wrong Choice #1");
        wrongChoiceTextField1.setPreferredSize(new java.awt.Dimension(64, 32));

        wrongChoiceTextField2.setBackground(QuizPanel.WRONG_COLOR);
        wrongChoiceTextField2.setFont(com.kierjohn.testgui.GlobalUtils.getFont(0, 16));
        wrongChoiceTextField2.setForeground(new java.awt.Color(255, 255, 153));
        wrongChoiceTextField2.setText("Wrong Choice #2");
        wrongChoiceTextField2.setPreferredSize(new java.awt.Dimension(64, 32));

        wrongChoiceTextField3.setBackground(QuizPanel.WRONG_COLOR);
        wrongChoiceTextField3.setFont(com.kierjohn.testgui.GlobalUtils.getFont(0, 16));
        wrongChoiceTextField3.setForeground(new java.awt.Color(255, 255, 153));
        wrongChoiceTextField3.setText("Wrong Choice #3");
        wrongChoiceTextField3.setPreferredSize(new java.awt.Dimension(64, 32));

        javax.swing.GroupLayout multipleChoiceFormPanelLayout = new javax.swing.GroupLayout(multipleChoiceFormPanel);
        multipleChoiceFormPanel.setLayout(multipleChoiceFormPanelLayout);
        multipleChoiceFormPanelLayout.setHorizontalGroup(
            multipleChoiceFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multipleChoiceFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(multipleChoiceFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wrongChoiceTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wrongChoiceTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wrongChoiceTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multipleCorrectAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        multipleChoiceFormPanelLayout.setVerticalGroup(
            multipleChoiceFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multipleChoiceFormPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(multipleCorrectAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wrongChoiceTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wrongChoiceTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wrongChoiceTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bottonFormPanelContainer.add(multipleChoiceFormPanel, "multiple");

        trueOrFalseFormPanel.setBackground(new java.awt.Color(106, 49, 144));
        trueOrFalseFormPanel.setPreferredSize(new java.awt.Dimension(600, 218));

        defaultBooleanLabel1.setBackground(new java.awt.Color(106, 49, 144));

        trueToggleBtn.setBackground(new Color(255, 255, 255));
        buttonGroup1.add(trueToggleBtn);
        trueToggleBtn.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 16)); // NOI18N
        trueToggleBtn.setSelected(true);
        trueToggleBtn.setText("True");

        falseToggleBtn.setBackground(new Color(255, 255, 255));
        buttonGroup1.add(falseToggleBtn);
        falseToggleBtn.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 16)); // NOI18N
        falseToggleBtn.setText("False");

        javax.swing.GroupLayout defaultBooleanLabel1Layout = new javax.swing.GroupLayout(defaultBooleanLabel1);
        defaultBooleanLabel1.setLayout(defaultBooleanLabel1Layout);
        defaultBooleanLabel1Layout.setHorizontalGroup(
            defaultBooleanLabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultBooleanLabel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(trueToggleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(falseToggleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        defaultBooleanLabel1Layout.setVerticalGroup(
            defaultBooleanLabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultBooleanLabel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(defaultBooleanLabel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trueToggleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(falseToggleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        correctAnswerLabe2.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 16)); // NOI18N
        correctAnswerLabe2.setForeground(new java.awt.Color(255, 242, 248));
        correctAnswerLabe2.setText("Answer:");

        javax.swing.GroupLayout trueOrFalseFormPanelLayout = new javax.swing.GroupLayout(trueOrFalseFormPanel);
        trueOrFalseFormPanel.setLayout(trueOrFalseFormPanelLayout);
        trueOrFalseFormPanelLayout.setHorizontalGroup(
            trueOrFalseFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trueOrFalseFormPanelLayout.createSequentialGroup()
                .addComponent(defaultBooleanLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 245, Short.MAX_VALUE))
            .addGroup(trueOrFalseFormPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(correctAnswerLabe2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        trueOrFalseFormPanelLayout.setVerticalGroup(
            trueOrFalseFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trueOrFalseFormPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(correctAnswerLabe2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(defaultBooleanLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        bottonFormPanelContainer.add(trueOrFalseFormPanel, "boolean");

        identificationFormPanel.setBackground(new java.awt.Color(106, 49, 144));
        identificationFormPanel.setPreferredSize(new java.awt.Dimension(600, 218));

        identificationAnswerTxtField.setBackground(new java.awt.Color(153, 153, 153));
        identificationAnswerTxtField.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 25)); // NOI18N
        identificationAnswerTxtField.setForeground(new java.awt.Color(255, 255, 255));
        identificationAnswerTxtField.setText("Correct Answer");
        identificationAnswerTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificationAnswerTxtFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout identificationFormPanelLayout = new javax.swing.GroupLayout(identificationFormPanel);
        identificationFormPanel.setLayout(identificationFormPanelLayout);
        identificationFormPanelLayout.setHorizontalGroup(
            identificationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, identificationFormPanelLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(identificationAnswerTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        identificationFormPanelLayout.setVerticalGroup(
            identificationFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(identificationFormPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(identificationAnswerTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bottonFormPanelContainer.add(identificationFormPanel, "identification");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE;
        formPanel.add(bottonFormPanelContainer, gridBagConstraints);

        barrier.setBackground(new java.awt.Color(51, 0, 51));
        barrier.setRequestFocusEnabled(false);

        javax.swing.GroupLayout barrierLayout = new javax.swing.GroupLayout(barrier);
        barrier.setLayout(barrierLayout);
        barrierLayout.setHorizontalGroup(
            barrierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        barrierLayout.setVerticalGroup(
            barrierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 605;
        gridBagConstraints.ipady = 12;
        formPanel.add(barrier, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        parent.remove(this);
        parent.revalidate();
        parent.repaint();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void qTypeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qTypeInputActionPerformed
        CardLayout card = (CardLayout) bottonFormPanelContainer.getLayout();
        card.show(bottonFormPanelContainer, getType());
    }//GEN-LAST:event_qTypeInputActionPerformed

    private void identificationAnswerTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificationAnswerTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificationAnswerTxtFieldActionPerformed

    protected String getType() {
        String qType = "identification";
        switch (((String) qTypeInput.getSelectedItem()).toLowerCase()) {
            case "multiple choice" -> qType = "multiple";
            case "true or false" -> qType = "boolean";
        }
        return qType;
    }
    
    protected void setIndex(int i) {
        index = i;
        indexLabel.setText(i + 1 + "");
    }
    
    protected int getIndex() {
        return index;
    }
    
    protected Question getQuestion() {
        String question = questionTextField.getText();
        switch (getType()) {
            case "multiple" -> {
                String[] wrongChoices = {
                    wrongChoiceTextField1.getText(),
                    wrongChoiceTextField2.getText(),
                    wrongChoiceTextField1.getText()
                };
                return new Question(question, multipleCorrectAnswer.getText(), wrongChoices);
            } case "boolean" -> {
                return new Question(question, trueToggleBtn.isSelected());
            } default -> {
                return new Question(question, identificationAnswerTxtField.getText());
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel barrier;
    protected javax.swing.JPanel bottonFormPanelContainer;
    protected javax.swing.ButtonGroup buttonGroup1;
    protected javax.swing.JLabel correctAnswerLabe2;
    protected javax.swing.JPanel defaultBooleanLabel1;
    protected javax.swing.JButton deleteBtn;
    protected javax.swing.JToggleButton falseToggleBtn;
    protected javax.swing.JPanel formPanel;
    protected javax.swing.JTextField identificationAnswerTxtField;
    protected javax.swing.JPanel identificationFormPanel;
    protected javax.swing.JLabel indexLabel;
    protected javax.swing.JPanel multipleChoiceFormPanel;
    protected javax.swing.JTextField multipleCorrectAnswer;
    protected javax.swing.JComboBox<String> qTypeInput;
    protected javax.swing.JTextField questionTextField;
    protected javax.swing.JLabel titleLabel;
    protected javax.swing.JPanel trueOrFalseFormPanel;
    protected javax.swing.JToggleButton trueToggleBtn;
    protected javax.swing.JPanel upperFormPanel;
    protected javax.swing.JTextField wrongChoiceTextField1;
    protected javax.swing.JTextField wrongChoiceTextField2;
    protected javax.swing.JTextField wrongChoiceTextField3;
    // End of variables declaration//GEN-END:variables
    private int index;
    protected String answer;
}
